name : reuseable
on: 
  workflow_call:
    inputs:   # used to get input 
        artifact-name :  # 
            description: The name of the deployable artifact files 
            required: false
            default: dist # default value 
            type: string
    outputs:  # used to print the output 
      result: 
        description: the result of the deployment operation 
        value : ${{ jobs.deploy.outputs.outcome}}
    # secrets:
    #     inputser :
    #       required: false
    
jobs:
  deploy:
    runs-on : ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }} #  this methood is used to get the result to output
    steps:
       - name: Get build artifacts
         uses: actions/download-artifact@v4
         with:
            name: ${{ inputs.artifact-name}}
       - name: list value
         run : ls
       - name: Output contents
         run: ls
       - name: Deploy
         run: echo "Deploying..."
       - name: set result output
         id: set-result
         run: echo "::set-output name=step-result::success"  # here we are setting the output as success
